// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyaKQ9NatWNXYbW9RwipoesRbA8gncIq0',
    appId: '1:976862139604:web:2a476930bb2414d3b99741',
    messagingSenderId: '976862139604',
    projectId: 'simuka-3c502',
    authDomain: 'simuka-3c502.firebaseapp.com',
    storageBucket: 'simuka-3c502.firebasestorage.app',
    measurementId: 'G-VTBFWPX7KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYge9uY_ejIKNNf6grZzWm6v5EaUCP0ig',
    appId: '1:976862139604:android:8c4c3c16f517651cb99741',
    messagingSenderId: '976862139604',
    projectId: 'simuka-3c502',
    storageBucket: 'simuka-3c502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvBOkO26pIk1_NYBf2yxOwSZ6oNtyoVkY',
    appId: '1:976862139604:ios:3ad978d528b40482b99741',
    messagingSenderId: '976862139604',
    projectId: 'simuka-3c502',
    storageBucket: 'simuka-3c502.firebasestorage.app',
    iosBundleId: 'com.example.simuka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvBOkO26pIk1_NYBf2yxOwSZ6oNtyoVkY',
    appId: '1:976862139604:ios:3ad978d528b40482b99741',
    messagingSenderId: '976862139604',
    projectId: 'simuka-3c502',
    storageBucket: 'simuka-3c502.firebasestorage.app',
    iosBundleId: 'com.example.simuka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyaKQ9NatWNXYbW9RwipoesRbA8gncIq0',
    appId: '1:976862139604:web:a433fdbea3937502b99741',
    messagingSenderId: '976862139604',
    projectId: 'simuka-3c502',
    authDomain: 'simuka-3c502.firebaseapp.com',
    storageBucket: 'simuka-3c502.firebasestorage.app',
    measurementId: 'G-8PMJDF47V9',
  );
}
